Repository super-cooper/memebot, pull requests merged in 2020-12, with the labels that each got.

#52 Commands module should automatically load commands
  src/commands/__init__.py
  src/commands/command.py
  src/commands/help/__init__.py
  src/commands/registry.py
  src/commands/role/__init__.py
  src/commands/role/create.py
  src/commands/role/delete.py
  src/commands/role/join.py
  src/commands/role/leave.py
  src/commands/role/list.py
Labels: codefix, low-priority

#60 Fix type annotations that were outdated or incorrect
  src/commands/command.py
  src/commands/command_output.py
  src/memebot.py
Labels: codefix

#62 Fix subcommand registration
  src/commands/__init__.py
Labels: bug, high-priority

#55 Command callbacks are called regardless of whether or not command fails
  src/commands/command.py
  src/commands/command_output.py
  src/commands/execution.py
  src/commands/role/__init__.py
  src/lib/status.py
Labels: bug, good first issue, low-priority

#66 !role list sorts output alphabetically
  src/commands/role/list.py
Labels: feature, low-priority

#44 Posts Embeded Quote Tweets and Media
  .gitignore
  requirements.txt
  src/lib/constants.py
  src/memebot.py
Labels: feature, low-priority

#65 Fix role double-join errors
  src/commands/role/__init__.py
  src/commands/role/join.py
Labels: bug, low-priority

#68 Support config through command-line parameters
  README.md
  src/config/__init__.py
  src/main.py
  src/memebot.py
Labels: feature, low-priority
