Repository super-cooper/memebot, pull requests merged in 2021-05, with the labels that each got.

#73 Initial database implementation
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  docker/Dockerfile
  docker/docker-compose.yaml
  requirements.txt
  src/commands/__init__.py
  src/commands/command.py
  src/config/__init__.py
  src/config/mongod.yaml
  src/db/__init__.py
  src/db/internals.py
  src/memebot.py
Labels: feature

#79 Fix container DNS speed issues
  docker/docker-compose.yaml
Labels: bug, high-priority

#80 Create logging subsystem
  README.md
  src/config/__init__.py
  src/config/validators.py
  src/log/__init__.py
  src/log/formatter.py
  src/log/logger.py
  src/main.py
  src/memebot.py
Labels: feature

#81 Marginally increase command parsing performance
  src/commands/command.py
  src/commands/execution.py
  src/commands/poll/__init__.py
  src/memebot.py
Labels: codefix, low-priority

#82 Use `functools.lru_cache` instead of `functools.cache`
  src/log/logger.py
Labels: bug, high-priority

#89 Extend `!help` command to accept names of other commands as arguments
  src/commands/command.py
  src/commands/hello/__init__.py
  src/commands/help/__init__.py
  src/commands/poll/__init__.py
  src/commands/role/__init__.py
  src/commands/role/create.py
  src/commands/role/delete.py
  src/commands/role/join.py
  src/commands/role/leave.py
  src/commands/role/list.py
Labels: feature

#90 Stop fetching quote tweets from own messages
  src/integrations/twitter.py
  src/memebot.py
Labels: bug, high-priority
