Repository super-cooper/memebot, pull requests merged in 2022-12, with the labels that each got.

#138 Upgrade to discord.py 2.1.0
  requirements.txt
  src/commands/help.py
  src/commands/poll.py
  src/commands/role.py
  src/memebot.py
Labels: high-priority

#136 Fix message for `!role list` commands
  src/commands/role.py
Labels: bug

#139 Properly annotate role subcommand arguments
  src/commands/role.py
Labels: low-priority, codefix
