Repository super-cooper/memebot, pull requests merged in 2022-10, with the labels that each got.

#121 Fix GitHub Action workflow triggers
  .github/workflows/black.yaml
  .github/workflows/codeql-analysis.yaml
  .github/workflows/docker.yaml
  .github/workflows/mypy.yaml
  .github/workflows/pytest.yaml
  .github/workflows/yamllint.yaml
  tests/test_pytest.py
Labels: bug, low-priority

#126 Convert role arguments to lowercase
  src/commands/role.py
Labels: bug

#130 Use latest version of cosign available for Docker workflow
  .github/workflows/docker.yaml
Labels: bug

#128 Add ability to list roles by user
  src/commands/role.py
Labels: feature
