Repository super-cooper/memebot, pull requests merged in 2022-08, with the labels that each got.

#115 Add spoiler tags to twitter links
  src/integrations/twitter.py
  src/lib/util.py
Labels: feature

#112 Use mypy for static type checking
  .dockerignore
  README.md
  docker-compose.yaml
  docker/Dockerfile
  docker/template.env
  pyproject.toml
  requirements.txt
  src/commands/hello.py
  src/commands/help.py
  src/commands/poll.py
  src/commands/role.py
  src/config/__init__.py
  src/db/__init__.py
  src/db/internals.py
  src/integrations/__init__.py
  src/integrations/twitter.py
  src/lib/__init__.py
  src/lib/constants.py
  src/log/__init__.py
  src/log/formatter.py
  src/log/logger.py
  src/main.py
  src/memebot.py
  tests/requirements.txt
Labels: low-priority

#116 Lint with black
  src/commands/hello.py
  src/commands/help.py
  src/commands/poll.py
  src/commands/role.py
  src/config/__init__.py
  src/config/validators.py
  src/integrations/twitter.py
  src/lib/constants.py
  src/log/__init__.py
  src/log/formatter.py
  src/log/logger.py
  src/main.py
  src/memebot.py
Labels: codefix
