Repository super-cooper/memebot, pull requests merged in 2023-01, with the labels that each got.

#140 Convert commands to slash commands
  src/commands/__init__.py
  src/commands/hello.py
  src/commands/help.py
  src/commands/poll.py
  src/commands/role.py
  src/lib/exception.py
  src/lib/util.py
  src/memebot.py
Labels: feature

#113 Use `emoji` library for emoji operations
  requirements.txt
  src/commands/poll.py
  src/integrations/twitter.py
  src/lib/constants.py
  src/log/logger.py
Labels: low-priority, codefix

#141 Switch Twitter integration to V2 API
  README.md
  docker/template.env
  requirements.txt
  src/config/__init__.py
  src/integrations/twitter.py
Labels: high-priority
